### PR TITLE
Convert Travis tests to GitHub actions

### PR DESCRIPTION
**Pull request by duboism**
Travis no longer gives free access to free projects. Therefore, this PR converts the test suite to GitHub actions.

# Technical details

Here are a few notes:
  - The test suite itself is not changed. It still work from 5.6 to 7.4
  - We use [Setup PHP Action](https://github.com/marketplace/actions/setup-php-action) to set up PHP.
  - `pear` must be run with `sudo`. Therefore, for now, we test only on Ubuntu and macOS because there is no `sudo` on Windows.
  - The action is configured to run on pull requests and when pushing on certain branches. 
  - The action can be launched manually from GitHub interface (at least from @duboism/HTML_Template_IT): go in the `Actions` tab, select `Main`  on the left and in the drop box, select branch `github_actions_master` and then click the `Run workflow` button.

# Relation to #15 and #17 

As of 2186e205cb7fde39b1a50a52e33441d17015e974, #15 is a bit buggy (conflicts in versions of `PHPUnit`).

This PR was developed to simplify the development of #15 but since then I found a better approach to modernize the test suite which is in #17.

#17 is based on this branch so merging this would greatly help.

### CODE REVIEW

**Comment by Neustradamus** [comment]
@duboism: Good job!

**Comment by duboism** [comment]
> @duboism: Good job!

Just to know: did you try to run the actions ?

**Comment by duboism** [comment]
@pear ?

**Comment by duboism** [comment]
By the way, I realized that some pear packages (like pear/pear-core) already moved to GitHub actions. AFAICS, the actions are similar to what I propose here but if somebody knows better, don't hesitate.

**Review by ashnazg — APPROVED** [review]

**Comment by duboism** [comment]
Thank you @ashnazg !

**Comment by Neustradamus** [comment]
Thanks to @duboism for this PR and @ashnazg for merging!
Good job!

Can you add "Issues" section?

**Comment by duboism** [comment]
> While paying a bit more attention to the test output, I noticed that PHPUnit warns about some deprecated code (namely, the dynamic creation of a property which is deprecated since PHP 8.2). I will address that in another PR.
> 
See #19 for that.

**Pull request merged**
