### PR TITLE
Convert the test suite to PHPUnitPolyFills and update to PHP 8

### PR DESCRIPTION
**Pull request by duboism**
This PR ports the test suite to  [PHPUniPolyFills](https://github.com/Yoast/PHPUnit-Polyfills) which allow the test suite to run on many versions of PHPUnit (this library is recommended on [PHPUnit home page](https://phpunit.de/supported-versions.html) so I think it's a robust solution).  Therefore, we can run on all current versions of PHP.

There is almost no change to the code itself except:
  - Test cases inherits from `Yoast\PHPUnitPolyfills\TestCases\TestCase` so they must implement `set_up`/`tear_down` (instead of `setUp`/`tearDown`). See the doc [here](https://github.com/Yoast/PHPUnit-Polyfills?tab=readme-ov-file#testcases).
  - I suppressed the file `AllTests.php` because I could not port it. AFAIU, it doesn't change the tests.

**This PR is based on the branch used for PR #16 (so this one must be merged first and I must rebase)**. It only adds d6dd558 and  74c8855.

Also it replaces #15.

### CODE REVIEW

**Comment by Neustradamus** [comment]
@duboism: Thanks for this new PR, hope that @pear team will look it...

**Comment by Neustradamus** [comment]
The @pear team is down? :/

There are 2 recent PRs in this repository.

At the same time, it is possible to add the "Issues" section?

Thanks in advance.

Note: @schengawegga has done a lot of works recently...

**Review by ashnazg — APPROVED** [review]

**Comment by duboism** [comment]
Thank you @ashnazg !

**Comment by Neustradamus** [comment]
Thanks to @duboism for this PR and @ashnazg for merging!
Good job!

Can you add "Issues" section?

**Pull request merged**
